# Generated by Django 3.2.8 on 2021-10-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_pssenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pssenger',
            new_name='Passenger',
        ),
    ]
