# Generated by Django 4.0.2 on 2022-04-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decidir', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='receitas',
            new_name='receita',
        ),
    ]
